# Generated by Django 3.0.3 on 2020-06-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0003_auto_20200526_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=30)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='api_user.AppUser')),
            ],
            options={
                'db_table': 'Children',
            },
        ),
    ]
