# Generated by Django 3.0.3 on 2020-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'AppUser',
            },
        ),
    ]
