# Generated by Django 3.0.3 on 2020-05-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table='Appuser',
        ),
    ]
