# Generated by Django 3.0.3 on 2020-06-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_auto_20200602_1505'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userimage',
            table='Userimage',
        ),
    ]
