# Generated by Django 3.0.3 on 2020-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20200602_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='uimage',
            field=models.ImageField(default='none/no-img.jpg', upload_to=''),
        ),
    ]
