# Generated by Django 3.0.3 on 2020-06-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_auto_20200602_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprofile', models.ImageField(default='none/no-img.jpg', upload_to='userprofile')),
            ],
            options={
                'db_table': 'Userprofile',
            },
        ),
        migrations.AlterField(
            model_name='userimage',
            name='uimage',
            field=models.ImageField(default='none/no-img.jpg', upload_to='userimage'),
        ),
    ]
