# Generated by Django 3.0.3 on 2020-06-09 09:15

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_auto_20200609_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='uimage',
            field=models.ImageField(default='none/no-img.jpg', storage=image_app.models.OverwriteStorate(), upload_to='userimage'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uprofile',
            field=models.ImageField(default='none/no-img.jpg', storage=image_app.models.OverwriteStorate(), upload_to='userprofile'),
        ),
    ]
